export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            background: "grey",
            padding: "1rem",
            position: "absolute",
            top: 0,
            right: 0,
            left: 0,
            color: "white",
            fontSize: "20px"
          }}
        >
          Navbar
        </header>
        <div style={{ marginTop: "4rem" }}>{children}</div>
        <footer
          style={{
            background: "slategrey",
            padding: "1rem",
            position: "absolute",
            bottom: 0,
            right: 0,
            left: 0,
            color: "white",
            fontSize: "20px",
            textAlign: "center",
          }}
        >
          &copy; 2024 | All rights resevered | Developed by Murtaza
        </footer>
      </body>
    </html>
  );
}
